### ISSUE TITLE
Pressure Advance Mistake

### ISSUE THREAD

**Issue by arismelachroinos** [bootuz-dinamon/ender3-v3-se-full-klipper#1]
I believe you made a mistake on the pressure advance value. 
I think you multiplied the mm with 0.02 instead of 0.005. 
Instead of 0.17, I think the correct value is somewhere around 0.065..

**Comment by arismelachroinos** [comment]
anyhow, thanks for your tutorial video & config files, they helped me a lot.

**Comment by bootuz-dinamon** [comment]
I will be grateful if you saddle up your test on Pressure Advance and publish your data. I recalculated my cube and it came out to about 0.135.

**Comment by arismelachroinos** [comment]
Here is my result: 
![image](https://github.com/bootuz-dinamon/ender3-v3-se-full-klipper/assets/21193898/4b811d10-e1f0-424c-9182-67b0d5af46e5)
I am measuring 11.24mm from the bottom of the print, where I believe the corners are of the best quality. I am multiplying 11.24*0.005 = 0.0562

**Comment by arismelachroinos** [comment]
Please let me know if I am doing something wrong.

**Comment by bootuz-dinamon** [comment]
pressure_advance: 0.04

**Comment by arismelachroinos** [comment]
This seems a lot more reasonable

**Comment by arismelachroinos** [comment]
This seems a lot more reasonable
