### ISSUE TITLE
Klipper Ender 3 V3 KE

### ISSUE THREAD

**Issue by weismantelf** [bootuz-dinamon/ender3-v3-se-full-klipper#3]
Hello,
I saw your video on you tube about the Ender 3 V3 KE.
Great job!

How can I use full klipper version on Ender 3 V3 KE?

Would be nice, if you can help.

**Comment by bootuz-dinamon** [comment]
To do this, you will need the correct printer.cfg (I think that very soon they will already be on the Internet), you will need a single-board computer like Orange pi Zero 3. And you can buy a USB-UART cable from Creality -https://s.click.aliexpress.com/e/_DlkYQB3

**Comment by weismantelf** [comment]
Thx
